/* Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main(void)
{
    int term1 = 1;
    int term2 = 2;
    int term3 = term1 + term2;
    int sum = 0;
    int sum_even = 0;
    
    do
    {
        //printf("%i\n", term1);
        sum += term1;
        sum_even += term1 % 2 == 0 ? term1 : 0;
        term1 = term2;
        term2 = term3;
        term3 = term1 + term2;
    } while (term1 < 4000000);
    
    printf("sum: %i, sum_even: %i\n", sum, sum_even);
}